version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: elevenlabs_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: elevenlabs_clone
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - elevenlabs_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: elevenlabs_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=elevenlabs_clone
    depends_on:
      - mongodb
    networks:
      - elevenlabs_network
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elevenlabs_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - elevenlabs_network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  mongodb_data:

networks:
  elevenlabs_network:
    driver: bridge